replicaCount: 1

image:
  repository: Image repository path
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: The name of the static IP address
    ingress.gcp.kubernetes.io/pre-shared-cert: Name of the SSL certificate
    kubernetes.io/ingress.allow-http: "true"
    ingress.gcp.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: The domain name for the portfolio
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
